collections:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /blog/:slug

plugins:
  - jekyll-redirect-from

highlighter: rouge

exclude: ["README.md"]