services:
  prod-jekyll:
    container_name: prod-jekyll
    image: custom-jekyll:latest
    ports:
    # - external:internal
      - 3999:3999
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Stockholm
    restart: unless-stopped

networks:
  default:
    name: gravel
    external: true